### ISSUE TITLE
1.20 😤

### ISSUE THREAD

**Issue by CormacZ** [MrMelon54/multiple-server-lists-fabric#11]

**Comment by mrmelon54** [comment]
I don't like that tone of voice

I'm working on 1.20 versions of all my mods, but obviously, I can't work on them all at the same time.

**Comment by CormacZ** [comment]
> I don't like that tone of voice
> 
> I'm working on 1.20 versions of all my mods, but obviously, I can't work on them all at the same time.

Sorry 😓

**Comment by mrmelon54** [comment]
quick update: 1.20 release is now closer than ever

**Comment by mrmelon54** [comment]
I released 1.20 since the last update
