### ISSUE TITLE
Crashes on 1.19.1 when clicking "Multiplayer"

### ISSUE THREAD

**Issue by Auzathoth** [MrMelon54/multiple-server-lists-fabric#3]
On Curseforge, version 3.0.0 is marked available for 1.19.1, but it crashes when accessing the Multiplayer screen.
[latest.log](https://github.com/MrMelon54/multiple-server-lists-fabric/files/9275273/latest.log)

**Comment by mrmelon54** [comment]
Fixed in 3.0.2
