### ISSUE TITLE
Enhancements Abusement_Gaming

### ISSUE THREAD

**Issue by mrmelon54** [MrMelon54/multiple-server-lists-fabric#6]
[Discord message](https://discord.com/channels/571615112570601503/855361283364093952/1008906061580869726)

```markdown
+ Web Browser Type Bar (Moveable Tabs) as pictured
+ Search Bar to find server faster if  you have a large amount of servers like me.
+ Custom Server Tags (so you can filter types of servers or versions) i.e PVP, 1.9, Pixelmon, Tech
+ Unlimited Legnth Server Names (Currently I have to use NBT Explorer to do so)
+ Custom Color Server names like the minimotd plugin
+ I have more ideas if you want to pick my brain
```

**Comment by mrmelon54** [comment]
Example tabs picture
![image](https://user-images.githubusercontent.com/48031324/184828773-8a38455e-cd4f-455d-91f1-f42070346244.png)

**Comment by AbusementGaming** [comment]
Ideas Expanded:
[Server Title Length]
Default Max is 31 Characters; Would be nice not to have a limit.
![image](https://user-images.githubusercontent.com/17483964/184964457-3852ceeb-ed42-4093-8e65-f5883be96027.png)

-Ability to use custom server-icons (locally stored
-Ability to use custom server motd (locally stored) 
-Ability to use a master server list. (sync server list across multiple versions of minecraft with the same client mod)

[Color Text]
The ability too use Color Text:
![image](https://user-images.githubusercontent.com/17483964/184965529-11ed85b0-bdae-45dd-b184-a2e3f2f26105.png)
https://docs.adventure.kyori.net/minimessage/format.html#

That's it for now.
