### ISSUE TITLE
1.19.3 support - waiting on myself

### ISSUE THREAD

**Issue by MelonHell** [MrMelon54/multiple-server-lists-fabric#7]

**Comment by mrmelon54** [comment]
First: does the 1.19.2 version work on 1.19.3?
Second: report any issues with the 1.19.2 version running on 1.19.3.
Third: if there are no issues I'll just update the version numbers to say it supports 1.19.3.

**Comment by MelonHell** [comment]
quilt + some mods + multiple-server-lists-mc1.19.1-3.0.2+build.10
[crash-2022-12-08_16.28.48-client.txt](https://github.com/MrMelon54/multiple-server-lists-fabric/files/10185776/crash-2022-12-08_16.28.48-client.txt)
[latest.log](https://github.com/MrMelon54/multiple-server-lists-fabric/files/10185784/latest.log)

**Comment by MelonHell** [comment]
fabric (latest) + fabric api (latest) + multiple-server-lists-mc1.19.1-3.0.2+build.10
[crash-2022-12-08_16.31.55-client.txt](https://github.com/MrMelon54/multiple-server-lists-fabric/files/10185806/crash-2022-12-08_16.31.55-client.txt)

[latest.log](https://github.com/MrMelon54/multiple-server-lists-fabric/files/10185807/latest.log)

**Comment by mrmelon54** [comment]
looks like an issue with the libgui version
https://github.com/CottonMC/LibGui/issues/178

**Comment by mrmelon54** [comment]
I have since been told it's an issue with jankson-fabric so I cross posted there as well

**Comment by byquanton** [comment]
#8
